### ISSUE TITLE
nats jetstream

### ISSUE THREAD

**Issue by gedw99** [goadesign/pulse#3]
we could also use nats jetstream instead of redis Or offer both.

the replicated maps pattern looks like a really good match.

Nats can use expsoe web sokets just like the existing redis example:
https://docs.nats.io/running-a-nats-service/configuration/websocket
https://satish860.hashnode.dev/running-nats-as-websocket-server

here is a simple nats pub sub example:
https://github.com/ConnectEverything/nats-by-example/blob/main/examples/messaging/pub-sub/go/main.go

---

You can embed the NATS server OR run it independently too. 

Here is a good example of how Kine does it using nats:
https://github.com/k3s-io/kine/tree/master/pkg/drivers/nats/server

---

NATS has contexts which can make running larger multi-tenant systems possible using the nsc nats tool.

https://github.com/nats-io/nsc
https://nats-io.github.io/nsc/

**Comment by raphael** [comment]
That sounds interesting, would be happy to review a PR or more detailed proposal on how that would work for the various packages.
